[tool.isort]
profile = "black"
known_first_party = ["app"]

[tool.black]
line-length = 88
target-version = ["py312"]  # Updated from py311

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
